[package]
name = "adventofcode2022"
version = "0.1.0"
authors = ["Cameron White <cameronwhite91@gmail.com>"]
edition = "2021"

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
parse-display = "0.7"
regex = "1.7"
itertools = "0.10"
